name: mqtt_client
description: A server side MQTT client for Dart supporting both secure sockets and websockets.
version: 5.6.3
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^1.1.0'
 path: '^1.6.4'
 crypto: '^2.1.3'
 meta: '^1.1.8'

dev_dependencies:
 test: '^1.3.0'
 mockito: '^3.0.0'

