name: mqtt_client
description: A server side MQTT client for Dart supporting both secure sockets and websockets.
version: 5.6.3
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 typed_data: ^1.3.0
 event_bus: ^2.0.0
 path: ^1.8.0
 crypto: ^3.0.1
 meta: ^1.7.0

dev_dependencies:
 test: ^1.17.11
 mockito: ^5.0.15

